module.exports = [
  {path: '#',
  title: 'Home',},
  {path: '#',
  title: 'Contact',},
  {path: '#',
  title: 'About',},
  {path: '#',
  title: 'Peanut Butter Jam Sandwich',},
  {path: '#',
  title: 'Apple With Syrup',},
  {path: '#',
  title: 'Home',},
  {path: '#',
  title: 'Contact',},
  {path: '#',
  title: 'About',},
  {path: '#',
  title: 'Peanut',},
  {path: '#',
  title: 'Apple With Cider Vingar',},
  {path: '#',
  title: 'Home Sweet Home No Where Better Than Home Yes!',},
  {path: '#',
  title: 'Contact',},
  {path: '#',
  title: 'About',},
  {path: '#',
  title: 'Peanut',},
  {path: '#',
  title: 'Apple',},
];;